sudo: required

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "XjmnUyqkR16TXKteSntq4SEj3i3CreM/a3pA34yZJnogK8YWc+JXoEaLdXTl3R8zSIqXRZpRltfiVS9PDDmW161mKBkX6J24nisv17LtgFC0MNz9JglKJvHc/m3eChukcFyfuC2ZuRMB5SmLgwj1c1Oer1TMGSleYBGC4d50O0gW5H8fKpQgdqU/bZ+2yzi1omNzFCWBAHg2WeWVI7qFjCD7PKHyACCMDbhLr4PmXD5BPbhHojBYn/VB44gBaKUv+qzSPW1aEfT3CcSDkq/XrEq/4jzGiyJ2ocH9Rlx8SYTkHlS2u1tyNdlszbf+xcc8M86JOZrjgFpA0lyj9T2Tg6WnbQFesS88+9YVx7+v4HAt+oEeG3B59jFr1t2Swuq9WswwpSd/zzdX5p4qqhatFhWu8bE1aHg38YZ7b5zhpyJy+XDUSsS5eR0qUAiqaF1oqcOm97FCkabmaNV6uz8v/IiDDWvP4e6FCPYW4WnKZDN67qUo5dfn8ioZGe+isj7VaxKaK0NHfb5jltpp+3oUrhJaLUoF02DlJOxpPacxZD326MxyjcZw4BoZ3seriSSZTP/usunPFgdS0WjWC5l4SRXTW5VwUQinBtyy31Qplqke6KXgnLI/NGmLp6KxYw8L1rEWnhcxroSBP/wo3NJi2ivzCGLyqKMBdznDvzZepTU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "ALcBNp1jZ3y8/VmCfEP4q0Ksxrzs8eiPpfQiZ+eCAqW8qPAYMTUYWvCtJZkfyOU+qLxltJT08H8eGaDYVgyoMmkvgk3gacHcmno28SRS5dR+8GezLSpIg52xizTO+tKWQRmQPtxTmgSBzTbb0x2YVvMw4Oz+c07JuRg30J7k+M6M20scIQFBW/cIf03JP0EoVs8UZ+K1c5MBvK4ukK+2vMmfB2FTxq9MEAT9a2RXWTtojku5eS3sHMNAEMnuePAB+GoMsu12Sq7FRNgDI8pZAkb4BzuJ7SNCz2yEHnbNVBv2rfK2Eaid6uNG/CCIO6uaTKUwQbIc+iZAfmLut8s1sGQYWvzbwEif5SwJNPKeLRRSksE9AGlNWykl1D2BWDXFZpzTgCKqfsX4G10WaSklWNhE7INCS7jjHcm9o7uLJk1ssF/McslQDUOl2bDWN9sFix2O+voMUuwXwAytsYS/ISmUBHd05DtA24I4kS0LfmU4Ew6BV0jbaD3CQ3fJdlkvJDwn4UL+WogR76Git9dxYabHP6Aq0hXLyb2xwqUpPp0Lzmuc7uxCoPDerJwEF5bh5RNsM3NOjFRArT0UPJWIXG39f7xgvOSX5n1Gr5pZho/QdjcDzOCZMuNA1WPQBDgQUo9dRAUhEdwcwW8dEc4THXP3iPYczsxV+Gv2X0VOqAg="

matrix:
  include:
    - stage: test
      language: node_js
      node_js:
        - 14
      addons:
        chrome: stable
      cache:
        directories:
          - $HOME/.m2
          - $HOME/.cache
        npm: true

      before_install:
        # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
        # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - cd src/main/app

      install:
        - npm ci --no-audit --prefer-offline
        - npm run build:test

      script:
        - npm run test:ci

    - stage: test
      language: java
      jdk:
        - openjdk11
      services:
        - docker

      cache:
        directories:
          - $HOME/.m2

      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh

      script:
        - mvn clean install

        - mv target/konfo-ui-*.jar $DOCKER_BUILD_DIR/artifact/konfo-ui.jar
        - cp -vr src/main/resources/* $DOCKER_BUILD_DIR/config/

        - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
        - export ARTIFACT_NAME="konfo-ui"
        - ./ci-tools/common/pull-image.sh
        - ./ci-tools/build/build-fatjar.sh konfo-ui
        - ./ci-tools/build/upload-image.sh $ARTIFACT_NAME --skip-dynamo-write

    - stage: deploy
      script:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh
        - export ARTIFACT_NAME="konfo-ui"
        - export BASE_IMAGE="baseimage-fatjar:master"
        - ./ci-tools/build/upload-image.sh $ARTIFACT_NAME --dynamo-write
